#!/usr/bin/env python3
"""Generate registry coverage TOML for matcher fixture and inventory JSON."""

from __future__ import annotations

import argparse
from dataclasses import asdict, dataclass
import json
from pathlib import Path
import re
import sys
import tomllib
from typing import Any, Iterable


APP_DIR = Path(__file__).resolve().parents[1]
REPO_DIR = APP_DIR.parent

DEFAULT_FIXTURE_FILE = APP_DIR / "languages" / "sv" / "matcher_contracts" / "matcher_regression_cases.json"
DEFAULT_INVENTORY_FILE = APP_DIR / "languages" / "sv" / "matcher_contracts" / "matcher_rule_inventory.json"
DEFAULT_ENTRIES_DIR = APP_DIR / "languages" / "sv" / "ingredient_matching" / "term_registry" / "entries"
REGRESSION_COVERAGE_FILE = "matcher_regression_case.toml"
INVENTORY_COVERAGE_FILE = "matcher_rule_inventory.toml"

HEADER_LINES_BY_KIND = {
    "fixture": [
        "# AUTO-GENERATED - DO NOT EDIT BY HAND.",
        "# Generated by support_checks/generate_matcher_registry_coverage.py.",
        "# Source: app/languages/sv/matcher_contracts/matcher_regression_cases.json",
        "# Manual additions must be marked with '# manual-coverage' immediately before a [[entries]] block.",
        "",
        "# Registry coverage for matcher_regression_cases.json fixtures.",
        "# The fixture JSON remains the executable regression source; these entries",
        "# make each accepted fixture row visible to the term-registry gate.",
    ],
    "inventory": [
        "# AUTO-GENERATED - DO NOT EDIT BY HAND.",
        "# Generated by support_checks/generate_matcher_registry_coverage.py.",
        "# Source: app/languages/sv/matcher_contracts/matcher_rule_inventory.json",
        "# Manual additions must be marked with '# manual-coverage' immediately before a [[entries]] block.",
        "",
        "# Registry coverage for matcher_rule_inventory.json rows.",
        "# The inventory JSON remains the diagnostic contract source; these entries",
        "# make each accepted inventory row visible to the term-registry gate.",
    ],
}


@dataclass(frozen=True)
class GeneratedEntry:
    source_id: str
    source_ref: str
    block: str


@dataclass(frozen=True)
class GeneratedCoverageFile:
    path: Path
    current_text: str
    generated_text: str
    generated_entry_count: int
    manual_block_count: int

    @property
    def changed(self) -> bool:
        return self.current_text != self.generated_text

    def to_summary(self, *, repo_root: Path) -> dict[str, Any]:
        return {
            "path": _rel(self.path, repo_root=repo_root),
            "changed": self.changed,
            "generated_entry_count": self.generated_entry_count,
            "manual_block_count": self.manual_block_count,
        }


def _app_dir_for_tree_root(tree_root: Path | None) -> Path:
    if tree_root is None:
        return APP_DIR
    root = tree_root.resolve()
    if (root / "app").is_dir():
        return root / "app"
    return root


def _repo_root_for_tree_root(tree_root: Path | None) -> Path:
    app_dir = _app_dir_for_tree_root(tree_root)
    return app_dir.parent if app_dir.name == "app" else app_dir


def _rel(path: Path, *, repo_root: Path) -> str:
    try:
        return str(path.resolve().relative_to(repo_root.resolve()))
    except ValueError:
        return str(path)


def _load_json_list(path: Path) -> list[dict[str, Any]]:
    payload = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(payload, list):
        raise ValueError(f"expected list payload in {path}")
    return payload


def _slug(value: str, *, fallback: str = "term") -> str:
    normalized = str(value or "").strip().lower()
    normalized = normalized.replace("å", "a").replace("ä", "a").replace("ö", "o")
    slug = re.sub(r"[^a-z0-9]+", "_", normalized).strip("_")
    return slug or fallback


def _toml_string(value: str) -> str:
    return json.dumps(str(value), ensure_ascii=False)


def _toml_array(values: Iterable[str]) -> str:
    return "[" + ", ".join(_toml_string(value) for value in values) + "]"


def _manual_blocks(text: str) -> list[str]:
    lines = text.splitlines()
    blocks: list[str] = []
    index = 0
    while index < len(lines):
        if not lines[index].strip().startswith("# manual-coverage"):
            index += 1
            continue
        start = index
        index += 1
        while index < len(lines) and lines[index].strip() != "[[entries]]":
            index += 1
        if index >= len(lines):
            blocks.append("\n".join(lines[start:]).rstrip())
            break
        index += 1
        while index < len(lines):
            stripped = lines[index].strip()
            if stripped.startswith("# manual-coverage") or stripped == "[[entries]]":
                break
            index += 1
        blocks.append("\n".join(lines[start:index]).rstrip())
    return [block for block in blocks if block]


def _existing_source_order(path: Path, source_ref_prefix: str) -> dict[str, int]:
    if not path.exists():
        return {}
    try:
        payload = tomllib.loads(path.read_text(encoding="utf-8"))
    except tomllib.TOMLDecodeError:
        return {}
    order: dict[str, int] = {}
    for index, entry in enumerate(payload.get("entries") or []):
        if not isinstance(entry, dict):
            continue
        source_refs = entry.get("source_refs") or []
        if not isinstance(source_refs, list):
            continue
        for source_ref in source_refs:
            if not isinstance(source_ref, str) or not source_ref.startswith(source_ref_prefix):
                continue
            source_id = source_ref.rsplit(":", 1)[-1]
            order.setdefault(source_id, index)
    return order


def _ordered_entries(entries: list[GeneratedEntry], *, existing_order: dict[str, int]) -> list[GeneratedEntry]:
    source_position = {entry.source_id: index for index, entry in enumerate(entries)}
    return sorted(
        entries,
        key=lambda entry: (
            0 if entry.source_id in existing_order else 1,
            existing_order.get(entry.source_id, source_position[entry.source_id]),
            source_position[entry.source_id],
        ),
    )


def _fixture_expected_canonicals(payload: dict[str, Any]) -> list[str]:
    canonicals = []
    for item in payload.get("expected_matches") or []:
        if isinstance(item, dict) and item.get("canonical"):
            canonicals.append(str(item["canonical"]))
    allowed = payload.get("allowed_additional_matches") or {}
    if isinstance(allowed, dict):
        for key in ("allowed_canonicals", "forbidden_canonicals"):
            canonicals.extend(str(value) for value in allowed.get(key, []) if value)
    return sorted(set(canonicals))


def _fixture_canonical(payload: dict[str, Any]) -> str:
    return ", ".join(_fixture_expected_canonicals(payload)) or str(payload.get("policy_ref") or "")


def _fixture_layer_policy(payload: dict[str, Any], canonical: str) -> list[str]:
    if int(payload.get("expected") or 0) == 1:
        if str(payload.get("policy_ref") or "").startswith("keyword_extra_parent_"):
            return ["accepted_filter", "normal"]
        return ["normal"]
    if canonical != str(payload.get("policy_ref") or ""):
        return ["negative_guard_only"]
    return ["accepted_filter", "normal"]


def _fixture_entry_id(payload: dict[str, Any], canonical: str) -> str:
    fixture_id = str(payload["id"])
    policy_ref = str(payload.get("policy_ref") or canonical)
    policy_base = policy_ref[:-7] if policy_ref.endswith("_family") else policy_ref
    if fixture_id.startswith(f"{policy_base}_"):
        suffix = fixture_id[len(policy_base) + 1:]
        return f"sv-se.policy.{_slug(policy_ref)}.{_slug(suffix)}"
    return f"sv-se.policy.{_slug(canonical)}.{_slug(fixture_id)}"


def _entry_block(
    *,
    entry_id: str,
    canonical: str,
    variant: str,
    source_ref: str,
    layer_policy: list[str],
    notes: str,
    source_family: str,
    layer_role: str,
) -> str:
    lines = [
        "[[entries]]",
        f"entry_id = {_toml_string(entry_id)}",
        'language = "sv"',
        'market = "SE"',
        f"canonical = {_toml_string(canonical)}",
        'status = "active"',
        f"variants = {_toml_array([variant])}",
        "ingredient_terms = []",
        "offer_terms = []",
        "negative_guards = []",
        f"source_refs = {_toml_array([source_ref])}",
        f"layer_policy = {_toml_array(layer_policy)}",
        f"notes = {_toml_string(notes)}",
        "",
        "[[entries.coverage]]",
        f"source_family = {_toml_string(source_family)}",
        f"canonical = {_toml_string(canonical)}",
        f"variant = {_toml_string(variant)}",
        f"layer_role = {_toml_string(layer_role)}",
    ]
    return "\n".join(lines)


def _fixture_entries(fixtures: list[dict[str, Any]]) -> list[GeneratedEntry]:
    entries: list[GeneratedEntry] = []
    for payload in fixtures:
        fixture_id = str(payload["id"])
        canonical = _fixture_canonical(payload)
        offer = payload.get("offer") or {}
        variant = f"{fixture_id}: {offer.get('name', '')}"
        source_ref = f"fixture:matcher_regression_cases:{fixture_id}"
        layer_role = "positive_regression" if int(payload.get("expected") or 0) else "negative_regression"
        entries.append(GeneratedEntry(
            source_id=fixture_id,
            source_ref=source_ref,
            block=_entry_block(
                entry_id=_fixture_entry_id(payload, canonical),
                canonical=canonical,
                variant=variant,
                source_ref=source_ref,
                layer_policy=_fixture_layer_policy(payload, canonical),
                notes=f"Registry coverage for matcher regression fixture {fixture_id}.",
                source_family="matcher_regression_case",
                layer_role=layer_role,
            ),
        ))
    return entries


def _inventory_entries(inventory: list[dict[str, Any]]) -> list[GeneratedEntry]:
    entries: list[GeneratedEntry] = []
    for payload in inventory:
        item_id = str(payload["id"])
        canonical = str(payload.get("canonical") or item_id)
        source_ref = f"inventory:matcher_rule_inventory:{item_id}"
        entries.append(GeneratedEntry(
            source_id=item_id,
            source_ref=source_ref,
            block=_entry_block(
                entry_id=f"sv-se.policy.{_slug(canonical)}.{_slug(item_id)}",
                canonical=canonical,
                variant=canonical,
                source_ref=source_ref,
                layer_policy=["no_product_text", "normal"],
                notes=f"Registry coverage for matcher rule inventory row {item_id}.",
                source_family="matcher_rule_inventory",
                layer_role=str(payload.get("kind") or "inventory_rule"),
            ),
        ))
    return entries


def _generated_text(
    *,
    kind: str,
    entries: list[GeneratedEntry],
    target_path: Path,
    source_ref_prefix: str,
) -> str:
    current_text = target_path.read_text(encoding="utf-8") if target_path.exists() else ""
    ordered_entries = _ordered_entries(
        entries,
        existing_order=_existing_source_order(target_path, source_ref_prefix),
    )
    parts = ["\n".join(HEADER_LINES_BY_KIND[kind]).rstrip()]
    parts.extend(entry.block.rstrip() for entry in ordered_entries)
    manual_blocks = _manual_blocks(current_text)
    if manual_blocks:
        parts.append("# Preserved manual coverage blocks")
        parts.extend(manual_blocks)
    return "\n\n".join(parts).rstrip() + "\n"


def generate_coverage_files(
    *,
    tree_root: Path | None = None,
    fixture_file: Path | None = None,
    inventory_file: Path | None = None,
    entries_dir: Path | None = None,
) -> list[GeneratedCoverageFile]:
    app_dir = _app_dir_for_tree_root(tree_root)
    fixture_file = fixture_file or app_dir / "languages" / "sv" / "matcher_contracts" / "matcher_regression_cases.json"
    inventory_file = inventory_file or app_dir / "languages" / "sv" / "matcher_contracts" / "matcher_rule_inventory.json"
    entries_dir = entries_dir or app_dir / "languages" / "sv" / "ingredient_matching" / "term_registry" / "entries"
    regression_path = entries_dir / REGRESSION_COVERAGE_FILE
    inventory_path = entries_dir / INVENTORY_COVERAGE_FILE

    fixtures = _load_json_list(fixture_file)
    inventory = _load_json_list(inventory_file)
    outputs = [
        (
            regression_path,
            "fixture",
            _fixture_entries(fixtures),
            "fixture:matcher_regression_cases:",
        ),
        (
            inventory_path,
            "inventory",
            _inventory_entries(inventory),
            "inventory:matcher_rule_inventory:",
        ),
    ]
    generated_files: list[GeneratedCoverageFile] = []
    for path, kind, entries, source_ref_prefix in outputs:
        current_text = path.read_text(encoding="utf-8") if path.exists() else ""
        generated_files.append(GeneratedCoverageFile(
            path=path,
            current_text=current_text,
            generated_text=_generated_text(
                kind=kind,
                entries=entries,
                target_path=path,
                source_ref_prefix=source_ref_prefix,
            ),
            generated_entry_count=len(entries),
            manual_block_count=len(_manual_blocks(current_text)),
        ))
    return generated_files


def write_coverage_files(files: list[GeneratedCoverageFile]) -> list[Path]:
    changed: list[Path] = []
    for generated_file in files:
        if not generated_file.changed:
            continue
        generated_file.path.parent.mkdir(parents=True, exist_ok=True)
        generated_file.path.write_text(generated_file.generated_text, encoding="utf-8")
        changed.append(generated_file.path)
    return changed


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--tree-root", type=Path, default=None)
    parser.add_argument("--fixture-file", type=Path, default=None)
    parser.add_argument("--inventory-file", type=Path, default=None)
    parser.add_argument("--entries-dir", type=Path, default=None)
    parser.add_argument("--write", action="store_true", help="Update generated coverage TOML files.")
    parser.add_argument("--check", action="store_true", help="Fail if generated coverage TOML is stale.")
    parser.add_argument("--format", choices=("text", "json"), default="text")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    repo_root = _repo_root_for_tree_root(args.tree_root)
    files = generate_coverage_files(
        tree_root=args.tree_root,
        fixture_file=args.fixture_file,
        inventory_file=args.inventory_file,
        entries_dir=args.entries_dir,
    )
    changed = write_coverage_files(files) if args.write else []
    summaries = [item.to_summary(repo_root=repo_root) for item in files]
    if args.format == "json":
        print(json.dumps({
            "changed": [_rel(path, repo_root=repo_root) for path in changed],
            "files": summaries,
        }, ensure_ascii=False, indent=2, sort_keys=True))
    else:
        for summary in summaries:
            status = "updated" if summary["path"] in {_rel(path, repo_root=repo_root) for path in changed} else (
                "stale" if summary["changed"] else "current"
            )
            print(
                f"{status}: {summary['path']} "
                f"entries={summary['generated_entry_count']} manual={summary['manual_block_count']}"
            )
    if args.check and any(item.changed for item in files):
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
